name: Cron job for shutting down the APIs3
on:
    push:
    schedule:
        - cron: "*/1 * * * *"
jobs:
    report:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Shutting down API's
              run: |
                echo "Running job"
                chmod +x apis-shutdown.sh
                ./configuration/apis-shutdown.sh