name: Cron job for shutting down the APIs
on:
    schedule:
        - cron: "*/1 * * * *"
jobs:
    report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Shutting down API's
              run: echo "Running job"