name: Create test for cron job
on:
    schedule:
        - cron: "*/5 * * * *"
jobs:
    report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Creates a test for cron job
              run: echo "Running job right now"